version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: self-boardcast-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: examplepassword
      POSTGRES_DB: self_boardcast-db
    ports:
      - "5503:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: self-boardcast-redis
    ports:
      - "6379:6379"

volumes:
  db_data:
